### ISSUE TITLE
USER_AREA is not used anymore

### ISSUE THREAD

**Issue by Jimmi08** [LaocheXe/Falling-Holidays-eXeSystem#4]
This is not working anymore and lights are loaded in admin area

`if(vartrue($pluginpref['XMasLights'])  &&  USER_AREA) { `

**Comment by LaocheXe** [comment]
They change USER_AREA to something else then? Or did they just remove it completely?

**Comment by LaocheXe** [comment]
I notice a bunch of plugins still use USER_AREA - but also notice that e_IFRAME replaced it on the 11th of August?

https://github.com/e107inc/e107/search?q=USER_AREA&unscoped_q=USER_AREA

**Comment by Jimmi08** [comment]
in admin area it is not defined. No idea why, I just hot lights displayed in admin too.

**Comment by LaocheXe** [comment]
odd

**Comment by Jimmi08** [comment]
You are right. No idea what was wrong then.  But when I printed USER_AREA value, it said USER_AREA. 

I forgot that I have fork of this, so if this works for you, let it be.

![image](https://user-images.githubusercontent.com/5429548/93012155-273a6e00-f59e-11ea-84ac-faa686ca2ce8.png)
